@REM RUN A BATCH FILE COMMAND THAT WILL RUN A REACT WEB APP WHEN EXECUTED
@REM
@REM Author: 	iT Central
@REM Date: 	01/22/2022
@REM Version: 	1.0
@REM

@ECHO OFF
@SETLOCAL
@SET PATH=%PATH%;C:\Documents\REMS\web-rems

@REM CALL YARN INSTALL && YARN START IN THE PATH

@CALL yarn install
@CALL yarn start

@ENDLOCAL